### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by Roboe** [WeAreFairphone/android_packages_apps_MyApps#4]
Should we rename the repo to `android_packages_apps_MyApps`? That way we will follow the pattern convention in the AOSP-like ROMs, and coherence with the rest of the repos.

To do after renaming repo (or not):
 - [x] Setup [GitLab](https://gitlab.com/WeAreFairphone) mirror

**Comment by jannispinter** [comment]
Yes, I think we should rename the repo to ```android_packages_apps_MyApps```.

**Comment by Roboe** [comment]
Done! GitLab mirror has been set up, too
